### ISSUE TITLE
E1S3: Hidden village control unit is not really hidden

### ISSUE THREAD

**Issue by shikadiqueen** [project-ethea/After_the_Storm#1]
The village control unit on the bottom right corner of the game map in E1S3 is not hidden on 1.10.x or 1.11.x, even though there is a first_time_only=no preload event replicating the [hide_unit] implementation sans [redraw] targeting that unit.

**Comment by shikadilord** [comment]
This is mainline bug #21512: https://gna.org/bugs/?21512

**Comment by Vultraz** [comment]
In place of a village control dummy unit, you can use `defeat_condition=never` in the relevant [side] block. This will maintain flags on the villages without any units around.
