### ISSUE TITLE
Needs to use [object] to set player unit loyalty

### ISSUE THREAD

**Issue by shikadiqueen** [project-ethea/After_the_Storm#16]
See project-ethea/Invasion_from_the_Unknown#27.

**Comment by Konrad22** [comment]
Applies to Horo (Orcish Warrior), obtained in E1S7 - The Search for the Past.

**Comment by Konrad22** [comment]
For some reason Ergea and Cron (E3S7B) demand upkeep as well.

**Comment by shikadiqueen** [comment]
Units in E1S9.1 have `{TRAIT_LOYAL}` and the ones Mal Keshar spawns in E1S9.2 generally don't live for long enough to level up. So I'm considering this fixed now.
