### ISSUE TITLE
Question instead of issue regarding Death Baron

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#18]
Why are my skeletons unable to advance to Death Barons? (I'm still in Sc2, mind you. Maybe it's going to change soonish.)
(I noticed this because this differs from IftU. Just like that +50% XP for deteriorated.)

**Comment by shikadiqueen** [comment]
Balance purposes. AtS is supposed to lack units with leadership or slows until the late game, unlike IftU where they are commonplace.

**Comment by Konrad22** [comment]
Thanks.
