### ISSUE TITLE
E1S3 - Civil War in the North (suggestion)

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#20]
Add a lose condition for an enemy entering a ruined castle hex. As it is, I could just move out of the way, abandoning the town, making all my human allies homeless. (Considering how badly swords and arrows work against bones...I'd never need to do this.)
All the while Galas says things like 'We should defend this town!' or 'Oh no, we can't hold them, where are the reinforcements!' (Not exactly, but that's the gist of it.)
...to be fair, it doesn't make that much more sense when I'm easily defending the town either (swords/arrows vs bones). Maybe let him be a bit more chill about the situation? It's certainly not very desperate.

Maybe give Shamans a higher chance to be recruited?

**Comment by shikadiqueen** [comment]
Nope, this will make the scenario more annoying than it needs to be.
