### ISSUE TITLE
E1S4 - Terror at dusk, maybe changing the scenario objectives + extra

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#22]
As the long night is first and even longer, I can assasinate the two western leaders with my two shadows, while crushing the norther leader. This results in quite some surviving enemy units when the scenario ends.
So, maybe change the scenario objectives to defeating all enemy units, instead of just the leaders? I can't imagine that they'd let surviving enemies run rampart in the northern lands.

**Comment by Konrad22** [comment]
The blue enemy leader (Assault Drone) doesn't have the trait 'armored'. (The 2nd trait for that one is apparently random, resilient in 1.12, strong in 1.14.)

**Comment by shikadiqueen** [comment]
Requiring the player to kill every single unit would make the scenario more annoying than it needs to be. Most players can understand that generally once a side's leader is gone that side is somehow defeated for story purposes.
