### ISSUE TITLE
E1S9 - The Iron Triad - Part 2, event needs to be adapted

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#30]
When Elyssa ambushes you, she blows up the wall. Between the 1.12 version and the 1.14 you changed how exactly she blows up the wall, while apparently not touching the fighting part of the event. 
18,11 (where Elyssa was supposed to stand) is now an impassable stone wall, so she moves to 17,11 (two of the neighboring hexes are walls btw) instead, but Elynia still attacks 18,11 and Mal Keshar summons his undead to surround 18,11 as well.

**Comment by shikadiqueen** [comment]
I reckon this has something to do with the changes to `[terrain_mask]` @Vultraz was involved with.

**Comment by Vultraz** [comment]
Yes, I think you’ll need to either change some coordinates or set border= to.... something. False, probably.
