### ISSUE TITLE
E1S9 - The Iron Triad - Part 3, persisting something..?

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#32]
![screenshot_001](https://user-images.githubusercontent.com/39015360/44924407-7b71ad00-ad4b-11e8-8d94-5a578028a9ee.png)
This remains on the hex Elynia stood on when she used the teleport spell. It stays there until the scenario is over. (This happens only in 1.14.)

**Comment by shikadiqueen** [comment]
That looks like her wings' halo. Definitely an engine bug since nothing outside of her unit definitions ever reference it.

**Comment by Konrad22** [comment]
Could it be related to this one?
https://github.com/wesnoth/wesnoth/issues/3509

**Comment by newfrenchy83** [comment]
the commit in https://github.com/wesnoth/wesnoth/commit/9f633551ac7f79f83fde075550a5a022e23fefcb is the fix of this bug.

**Comment by newfrenchy83** [comment]
https://github.com/wesnoth/wesnoth/issues/3509 this two bugs différent foor me but with dame result

**Comment by Vultraz** [comment]
Is this still a thing?

**Comment by Konrad22** [comment]
Doesn't look like it. But I'd prefer if someone else confirmed this as well because it was pretty hard to spot to begin with.
[AtS-1-The Triad — Part 3-Auto-Save18.gz](https://github.com/project-ethea/After_the_Storm/files/3727903/AtS-1-The.Triad.Part.3-Auto-Save18.gz)

**Comment by Konrad22** [comment]
Doesn't look like it. But I'd prefer if someone else confirmed this as well because it was pretty hard to spot to begin with.
[AtS-1-The Triad — Part 3-Auto-Save18.gz](https://github.com/project-ethea/After_the_Storm/files/3727903/AtS-1-The.Triad.Part.3-Auto-Save18.gz)

**Comment by shikadiqueen** [comment]
I don't see it with SDL 2.0.10 at least. I'd like confirmation from someone who is using SDL 2.0.9.

**Comment by Vultraz** [comment]
Also don't see it. Running with 2.0.9. Guess the above fixes did work.
