### ISSUE TITLE
E1S10 - Tears, small question

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#34]
Why does the green enemy leader have the trait 'slow'? That's...weird.

**Comment by shikadiqueen** [comment]
`{TRAIT_SLOW} # NOTE: deliberate choice for now; not a mistake!`

**Comment by Konrad22** [comment]
Oops. I guess I should start looking at the WML before I report stuff. On a side note, I've finished Episode 1 on 1.12 (and now I'm sad) and I've almost finished it on 1.14.
