### ISSUE TITLE
E1S12 - The Queen, surviving enemies

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#38]
You are killing off any Shaxthal Drone and Psy Crawler. But that also means that you let every lvl 2 Shaxthal or Matrix Flow Systems live (not that those matter). Or the lvl 0 Worm (Shaxthal). That one doesn't matter either, but that's the one that's visible.
![screenshot_004](https://user-images.githubusercontent.com/39015360/45254030-c2c1f400-b370-11e8-8901-73c38efff80e.png)

**Comment by shikadiqueen** [comment]
Intentional.
