### ISSUE TITLE
E1S12 - The Queen, Mal Keshar is unhealable but can still drain enemies (Bossfight)

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#39]
I've been forgetting this one for days. But yeah. As the title says. That one is true in 1.12 as well.

**Comment by shikadiqueen** [comment]
This has been an issue since 1.10, for the record.

**Comment by shikadiqueen** [comment]
Removed all references to the unhealable status effect in commit 7bb0a08ce9e8591e6d1764d615b0e57fa83f1c2d, so this doesn't apply anymore.
