### ISSUE TITLE
E2S6 - The Voyage Home

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#42]
When Elynia warns Anya from the 'Errant Souls', she says that 'our' arcane 'fire' can easily dispell them.
But Elynia is the only one using arcane fire, Anya and Zynara use 'shadow wave' as their arcane attack.

**Comment by shikadiqueen** [comment]
The intention is that any arcane attack can cast errant spirits out of the world.

**Comment by Konrad22** [comment]
I'm aware, I'm just pointing out that Elynia is using wrong/very imprecise words to describe that fact.

**Comment by Konrad22** [comment]
In that case I request that you change her sentencse, so she says that her...nevermind, I finally noticed that no-one on my side is capable of wielding arcane fire at that point, so her words are not making much sense by any measure. There is no 'our arcane fire', there is not even 'my arcane fire'. ._.
So yeah...change her words so they make sense please? :(

**Comment by shikadiqueen** [comment]
Won't fix, especially now that Elynia *can* have faerie fire by this point in the campaign (which is up to the player of course).
