### ISSUE TITLE
E2S11 - A Final Confrontation, Control Spires get damaged in the end, but it doesn't show in their hp bar

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#47]
See title. Also, this worked in 1.12.

**Comment by shikadiqueen** [comment]
This works for me at the moment. Do you have a save where the issue still happens?

**Comment by Konrad22** [comment]
[AtS-2-A Final Confrontation-Auto-Save28.gz](https://github.com/project-ethea/After_the_Storm/files/2963776/AtS-2-A.Final.Confrontation-Auto-Save28.gz)
[AtS-2-A Final Confrontation replay.gz](https://github.com/project-ethea/After_the_Storm/files/2963778/AtS-2-A.Final.Confrontation.replay.gz)

**Comment by shikadiqueen** [comment]
I was looking at an unaffected save from before the `for`/`foreach` conversion, hence it didn't reproduce for me, oops.
