### ISSUE TITLE
E3S3 - Amidst the Ruins of Glamdrol, Nar-Hamoth leaving -> invalid WML

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#54]
When Nar-Hamoth left the field, this happened after the dialogue: 
**<**Invalid WML found**>** [unstore_unit]: variable 'second_unit' doesn't exist

**Comment by Vultraz** [comment]
I think this is caused by `FORCE_CHANCE_TO_HIT` somewhere. I have a feeling this might have been something I fucked up with my event refactoring...

**Comment by shikadiqueen** [comment]
Fixed in Naia commit 6f931ec55a55b10e40a3ec438aa828ecafea11c3.
