### ISSUE TITLE
Terraforming with Demolition/barrel explosions

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#57]
Demolition replaces water with dirt (1.12), while it ignores water in 1.14.

**Comment by Vultraz** [comment]
This is an odd one. The terrain filter (`terrain=A*,C*,D*,G*,K*,R*,U*`) doesn't include `W*`, but it never did... 🤔

**Comment by shikadiqueen** [comment]
It should ignore water so that means it's somehow working as intended where it didn't before.
