### ISSUE TITLE
E3S8d - Destiny - Part 2, wrong scenario objectives for Anya after defeating the Storm Sisters (or enemy leaders except the Iron Triad Lich)

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/After_the_Storm#66]
Anyas scenario objectives 'update' without changing it all. It still says that she has to defeat the 3 Storm Sisters. Durvans scenario objectives update correctly.
Happens in 1.12 and 1.14.

EDIT:
Updated the title because of the bug. Still true for both 1.12 and 1.14.

**Comment by shikadiqueen** [comment]
This is an issue that Inky had previously reported with the 1.12 version and even though I did manage to reproduce it, I couldn't figure out the cause or what she did that was special compared to my own playthroughs which may have triggered it.

**Comment by shikadiqueen** [comment]
Still happens in 1.14, and still no obvious cause or solution.

**Comment by shikadiqueen** [comment]
Finally determined the cause. The objectives refresh stops working properly as soon as the player reloads a save that isn't the start-of-scenario save for E3S8D.
