### ISSUE TITLE
E2S11: The boss fight needs more challenge

### ISSUE THREAD

**Issue by kabachuha** [project-ethea/After_the_Storm#80]
Hello, the AtS maintainers!

The scenario E2S11 'A Final Confrontation' is supposed to be as climatic and thrilling as the rest of AtS/IftU boss battles. However, it's challenge seems very diminished due to multiple reasons:

1. The player is very likely to get a rediculous carryover from the last scenario owing to a large number of villages. (More than 1000 gold)
2. The player can flood Hekuba's keep with units even without ghosts (with bats) and prevent him from additional recruiting.
3. The 'real boss', Ivyel presents almost no new threats and can be destroyed within one turn.

What do I suggest?

1. The gold carryover and/or the number of villages in S10 may be cut dramatically. (We have Elynia for healing anyway)
2. Hekuba's demons may be spawned in the chasms just like in IftU's E20 'The Heart' in addition to the keep, so the player won't be able to block new spawns and the player's army will be busy dealing with them.
3. Furthermore, to make things slightly more fun a few L3 demons may be showcased coming from the portal or Hekuba may launch an area of effect special attack.

Also, I think `dwarf-laugh.wav` during Hekuba's ambientance won't do any harm. 😈 

One of my replays is attached below. (Hard difficulty, ~1200 carried over starting gold, the boss fight was triggerred on turn 23, AtS version 0.10.3, Russian version)

[ПБ-2-Последняя битва повтор.gz](https://github.com/project-ethea/After_the_Storm/files/4976056/-2-.gz)

<details>
<summary>The screenshot taken during the middle of the boss fight</summary>

![A middle boss battle screenshot](https://user-images.githubusercontent.com/14872007/88464977-af1dc900-cec7-11ea-8619-386f6d38ddd7.png)
</details>

**Comment by shikadiqueen** [comment]
It just so happens that the latest release doesn't allow you to recruit bats anymore in E2.

I have had some ideas in mind for a long while, and one of them is sinking the player's economy throughout E2S9 and E2S10. I will be looking at the boss fight proper as well.
