### ISSUE TITLE
Terrains don't render on Wesnoth 1.15.3+dev

### ISSUE THREAD

**Issue by shikadiqueen** [project-ethea/After_the_Storm#81]
The following terrains don't render or only render tile transitions on Wesnoth 1.15.3+dev (dev branch tip) as of this writing:

* Starfield (`Xzsf`)
* Dry Elven Castle (`Cvz`)
* Dry Elven Castle Ruin (`Cvrz`)

(CC #71)

**Comment by newfrenchy83** [comment]
@shikadiqueen have you https://github.com/wesnoth/wesnoth/commit/c7d014453506bd827e20e737c4a384bf5cc48e40 in your copy of wesnoth master?

**Comment by shikadiqueen** [comment]
Not when I originally submitted this ticket, no. The next day or so I had a very long technical discussion with gfgtdf about the issue, which is what originated wesnoth/wesnoth#5012, which obviously fixes it. I just hadn't had a chance to test it until now.
